---

- name: Deploy kubernetes dashboard into cluster!
  when: init_cluster and started_kubelet and enable_dashboard
  command: |
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
  register: create_result
  until: create_result.rc == 0
  retries: 5
  delay: 2
  tags: dashboard
  become: yes
  become_user: genesys
  ignore_errors: false

- name: "Change dashboard service type to NodePort to expose to public network"
  shell: "kubectl patch service kubernetes-dashboard --namespace=kube-system  -p '{\"spec\": {\"type\": \"NodePort\"}}'"
  become: yes
  become_user: genesys

- name: create service account for dashboard
  shell: kubectl create serviceaccount genesysadmin
  become: yes
  become_user: genesys

- name: create cluster-admin role binding for dashboard
  shell: kubectl create clusterrolebinding genesysadmin-cadmin --clusterrole=cluster-admin --serviceaccount=default:genesysadmin
  become: yes
  become_user: genesys
  
- name: create admin role binding for dashboard
  shell: kubectl create clusterrolebinding genesysadmin-admin --clusterrole=admin --serviceaccount=default:genesysadmin
  become: yes
  become_user: genesys

- name: get login token for dashboard
  shell: kubectl -n default describe secret $(kubectl -n default get secret | awk '/^genesysadmin-token-/{print $1}') | awk '$1=="token:"{print $2}' 
  register: dashboard_token
  become: yes
  become_user: genesys

- name: save token to host
  local_action: copy content="{{ dashboard_token.stdout_lines[0] }}" dest="{{playbook_dir}}/dashboard_token"  

- name: show dashboard instructions
  debug: 
    msg: "Dashboard is available at https://<MASTER_NODE_IP>:6443/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/#!/node?namespace=default"

- name: show dashboard token
  debug: 
    msg: "The dashboard login token is: {{ dashboard_token.stdout_lines[0] }}"
